export const ALL_STUDENTS_REQUEST = 'ALL_STUDENTS_REQUEST'
export const ALL_STUDENTS_SUCCESS = 'ALL_STUDENTS_SUCCESS'
export const ALL_STUDENTS_FAIL = 'ALL_STUDENTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'